common:
  property: common value
some:
  property: common value

management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
  metrics:
    export:
      graphite:
        host: "172.17.0.2"
        port: 2003
        protocol: "plaintext"
        step: "5s"

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: "/admin/health"
    status-page-url-path: "/admin/info"
